steps:
  # 1. Build the container image
  # We use $_BUILD_CONFIG to tell Angular which environment.ts to use
  # We tag the image with the config name to keep them separate in the Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--build-arg",
        "BUILD_CONFIG=$_BUILD_CONFIG",
        "-t",
        "us-central1-docker.pkg.dev/$PROJECT_ID/angular-repo/my-app:$_BUILD_CONFIG",
        ".",
      ]

  # 2. Push the image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/$PROJECT_ID/angular-repo/my-app:$_BUILD_CONFIG",
      ]

  # 3. Deploy to Cloud Run
  # $_SERVICE_NAME will be 'angular-service' or 'angular-service-dev'
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "$_SERVICE_NAME"
      - "--image"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/angular-repo/my-app:$_BUILD_CONFIG"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"

# These are the default values if the trigger doesn't provide them
substitutions:
  _BUILD_CONFIG: production
  _SERVICE_NAME: angular-service

options:
  logging: CLOUD_LOGGING_ONLY
